package com.forever.tesistas.web.hibernate;
//default package
//Generated Nov 16, 2017 6:34:47 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* Address generated by hbm2java
*/
@Entity
@Table(name = "address", catalog = "cadena_licorerias")
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String numero;
	private String calle;
	private String colonia;
	private Date createTime;
	private Set<Distribuidor> distribuidors = new HashSet<Distribuidor>(0);
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Address() {
	}

	public Address(String numero, String calle, String colonia) {
		this.numero = numero;
		this.calle = calle;
		this.colonia = colonia;
	}

	public Address(String numero, String calle, String colonia, Date createTime, Set<Distribuidor> distribuidors,
			Set<Sucursal> sucursals, Set<Usuario> usuarios) {
		this.numero = numero;
		this.calle = calle;
		this.colonia = colonia;
		this.createTime = createTime;
		this.distribuidors = distribuidors;
		this.sucursals = sucursals;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "numero", nullable = false, length = 45)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "calle", nullable = false, length = 45)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "colonia", nullable = false, length = 45)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Distribuidor> getDistribuidors() {
		return this.distribuidors;
	}

	public void setDistribuidors(Set<Distribuidor> distribuidors) {
		this.distribuidors = distribuidors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
