package com.forever.tesistas.web.hibernate;
// default package

// Generated Nov 16, 2017 7:53:30 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "alcohol")
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String numero;
	private String calle;
	private String colonia;
	private Date createTime;

	public Address() {
	}

	public Address(String numero, String calle, String colonia) {
		this.numero = numero;
		this.calle = calle;
		this.colonia = colonia;
	}

	public Address(String numero, String calle, String colonia, Date createTime) {
		this.numero = numero;
		this.calle = calle;
		this.colonia = colonia;
		this.createTime = createTime;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "numero", nullable = false, length = 45)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "calle", nullable = false, length = 45)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "colonia", nullable = false, length = 45)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19, insertable = false)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "Address [id=" + id + ", numero=" + numero + ", calle=" + calle + ", colonia=" + colonia
				+ ", createTime=" + createTime + "]";
	}

}
