package com.forever.tesistas.web.hibernate;

// default package
// Generated Oct 31, 2017 12:11:00 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", catalog = "cadena_licorerias")
public class Factura implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Date fecha;
    private String vendedor;
    private String comprador;
    private Set<Producto> productos = new HashSet<Producto>(0);

    public Factura() {
    }

    public Factura(Date fecha) {
        this.fecha = fecha;
    }

    public Factura(Date fecha, String vendedor, String comprador, Set<Producto> productos) {
        this.fecha = fecha;
        this.vendedor = vendedor;
        this.comprador = comprador;
        this.productos = productos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha", nullable = false, length = 19)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "vendedor", length = 45)
    public String getVendedor() {
        return this.vendedor;
    }

    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }

    @Column(name = "comprador", length = 45)
    public String getComprador() {
        return this.comprador;
    }

    public void setComprador(String comprador) {
        this.comprador = comprador;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "factura")
    public Set<Producto> getProductos() {
        return this.productos;
    }

    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

}
