package com.forever.tesistas.web.hibernate;

//default package
//Generated Dec 6, 2017 11:38:04 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* LicorType generated by hbm2java
*/
@Entity
@Table(name = "licorType", catalog = "alcohol")
public class LicorType implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private Integer id;
	private String licorType;

	public LicorType() {
	}

	public LicorType(String licorType) {
		this.licorType = licorType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "licorType", nullable = false, length = 45)
	public String getLicorType() {
		return this.licorType;
	}

	public void setLicorType(String licorType) {
		this.licorType = licorType;
	}

	@Override
	public String toString() {
		return "LicorType [id=" + id + ", licorType=" + licorType + "]";
	}
	
	
	

}
