package com.forever.tesistas.web.hibernate;
//default package
//Generated Nov 16, 2017 5:00:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "alcohol")
public class Producto implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Distribuidor distribuidor;
    private Factura factura;
    private Sucursal sucursal;
    private String precio;
    private String presentacion;
    private int idDistribuidor;
    private String descripcion;
    private int stock;
    private Date createTime;
    private Set<Licor> licors = new HashSet<Licor>(0);

    public Producto() {
    }

    public Producto(Distribuidor distribuidor, Factura factura, Sucursal sucursal, String precio, String presentacion,
                    int idDistribuidor, int stock) {
        this.distribuidor = distribuidor;
        this.factura = factura;
        this.sucursal = sucursal;
        this.precio = precio;
        this.presentacion = presentacion;
        this.idDistribuidor = idDistribuidor;
        this.stock = stock;
    }

    public Producto(Distribuidor distribuidor, Factura factura, Sucursal sucursal, String precio, String presentacion,
                    int idDistribuidor, String descripcion, int stock, Date createTime, Set<Licor> licors) {
        this.distribuidor = distribuidor;
        this.factura = factura;
        this.sucursal = sucursal;
        this.precio = precio;
        this.presentacion = presentacion;
        this.idDistribuidor = idDistribuidor;
        this.descripcion = descripcion;
        this.stock = stock;
        this.createTime = createTime;
        this.licors = licors;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "distribuidor_id", nullable = false)
    public Distribuidor getDistribuidor() {
        return this.distribuidor;
    }

    public void setDistribuidor(Distribuidor distribuidor) {
        this.distribuidor = distribuidor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "factura_id", nullable = false)
    public Factura getFactura() {
        return this.factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sucursal_id", nullable = false)
    public Sucursal getSucursal() {
        return this.sucursal;
    }

    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }

    @Column(name = "precio", nullable = false, length = 45)
    public String getPrecio() {
        return this.precio;
    }

    public void setPrecio(String precio) {
        this.precio = precio;
    }

    @Column(name = "presentacion", nullable = false, length = 45)
    public String getPresentacion() {
        return this.presentacion;
    }

    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }

    @Column(name = "id_distribuidor")
    public int getIdDistribuidor() {
        return this.idDistribuidor;
    }

    public void setIdDistribuidor(int idDistribuidor) {
        this.idDistribuidor = idDistribuidor;
    }

    @Column(name = "descripcion", length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "stock", nullable = false)
    public int getStock() {
        return this.stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "licor_has_producto", catalog = "cadena_licorerias", joinColumns = {
            @JoinColumn(name = "producto_id", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "licor_id", nullable = false, updatable = false)})
    public Set<Licor> getLicors() {
        return this.licors;
    }

    public void setLicors(Set<Licor> licors) {
        this.licors = licors;
    }

}
